[package]
name = "brume"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
presage = { git = "https://github.com/whisperfish/presage.git", rev = "fde2eaa38fb99267305867923989725d2dd1300b" }
libsignal-service = { git = "https://github.com/whisperfish/libsignal-service-rs", rev = "456bf6eb2e4454ce35bdb4ca75b8dba7941c2923" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1.11"
hex = "0.4"
warp = "0.3"
futures = { version = "0.3", default-features=false}
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
log = "0.4.17"
env_logger = "0.10.0"
url = "2.2.2"
sled = "0.34.7"

[patch.crates-io]
"curve25519-dalek" = { git = 'https://github.com/signalapp/curve25519-dalek', branch = 'lizard2' }