name: Axolotl build pipeline

on:
  workflow_call:

env:
  GO_VERSION: 1.16
  NODE_VERSION: "18.x"

jobs:
  build-axolotl:
    name: Build axolotl
    runs-on: ubuntu-latest

    steps:
      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2

      - name: Sync node version and setup cache
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      
      - name: Check out code
        uses: actions/checkout@v3

      - name: Check
        run: make check-axolotl

      - name: Build
        run: make build-axolotl

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: axolotl
          path: axolotl
          retention-days: 1

  build-axolotl-web:
    name: Build axolotl-web
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Download dependencies
        run: npm --prefix ./axolotl-web ci --loglevel verbose

      - name: Run tests
        run: npm --prefix ./axolotl-web test

      - name: Lint application
        run: npm --prefix ./axolotl-web run lint

      - name: Analyze npm dependencies
        run: npm --prefix ./axolotl-web run depcheck

      - name: Build
        run: npm --prefix ./axolotl-web run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: axolotl-web
          path: axolotl-web/dist/
          retention-days: 1

  build-axolotl-deb-arm64:
    name: Build axolotl Debian arm64
    runs-on: ubuntu-latest

    steps:
      - name: Install Rust
        run: rustup update stable
      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: aarch64-unknown-linux-gnu

      - name: Rust cache
        uses: swatinem/rust-cache@v2

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build
        run: cargo build --release --target aarch64-unknown-linux-gnu --features tauri

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-arm64
          path: build/linux-arm64/axolotl
          retention-days: 1

  build-axolotl-web-deb-arm64:
    name: Build axolotl-web Debian arm64
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Create folder
        run: mkdir --parents $GITHUB_WORKSPACE/build/linux-arm64/axolotl-web

      - name: Download dependencies
        run: npm --prefix ./axolotl-web --target_arch=arm64 ci --loglevel verbose

      - name: Build
        run: npm --prefix ./axolotl-web --target_arch=arm64 run build

      - name: Copy build files
        run: |
          cp --recursive $GITHUB_WORKSPACE/axolotl-web/dist $GITHUB_WORKSPACE/build/linux-arm64/axolotl-web/
          cp --recursive $GITHUB_WORKSPACE/guis $GITHUB_WORKSPACE/build/linux-arm64/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-arm64
          path: build/linux-arm64/
          retention-days: 1
